require("magoz.options")
require("magoz.keymaps")
require("magoz.autocommands")
-- require("magoz.colorscheme")

require("magoz.plugins")

require("magoz.lsp")
require("magoz.plugins.cmp")
-- require("magoz.plugins.harpoon")
require("magoz.plugins.telescope")
require("magoz.plugins.treesitter")
require("magoz.plugins.autopairs")
require("magoz.plugins.nvim-surround")
-- require("magoz.plugins.comment")
require("magoz.plugins.true-zen")
-- require("magoz.plugins.which-key")
require("magoz.plugins.nvim-tree")
require("magoz.plugins.lualine")
require("magoz.plugins.project")
require("magoz.plugins.impatient")
require("magoz.plugins.illuminate")
require("magoz.plugins.nvim-colorizer")
require("magoz.plugins.indentline")
-- require("magoz.plugins.alpha")
require("magoz.plugins.trouble")
require("magoz.plugins.git")
-- require("magoz.plugins.dap")
-- require("magoz.plugins.copilot")
