require("user.options")
require("user.keymaps")
require("user.autocommands")
-- require("user.colorscheme")

require("user.plugins")

require("user.lsp")
require("user.plugins.cmp")
require("user.plugins.harpoon")
require("user.plugins.telescope")
require("user.plugins.treesitter")
require("user.plugins.autopairs")
require("user.plugins.nvim-surround")
require("user.plugins.comment")
require("user.plugins.true-zen")
require("user.plugins.which-key")
require("user.plugins.nvim-tree")
require("user.plugins.lualine")
require("user.plugins.project")
require("user.plugins.impatient")
require("user.plugins.illuminate")
require("user.plugins.nvim-colorizer")
require("user.plugins.indentline")
require("user.plugins.alpha")
require("user.plugins.trouble")
require("user.plugins.git")
-- require("user.plugins.dap")
-- require("user.plugins.copilot")
