// Test fixtures. `payloads.json` holds real Fleet wire payloads, generated by Fleet's own snapshot
// projection and checked against its schemas (see payloads.gen.ts); the builders below derive
// variations from those rows so every fixture keeps Fleet's current shape.
import payloads from './payloads.json' with { type: 'json' };

export { payloads };
export const NOW = payloads.now;
const minute = 60_000;

const realRows = payloads.snapshot.projects.flatMap((p) => p.worktrees.flatMap((w) => w.rows));
export const realRow = (id) => structuredClone(realRows.find((r) => r.id === id));

/** A root row shaped like Fleet's `FleetRow` (from a real one), in `state` (own state too). */
export function wireRow(id, state, extra = {}) {
  const base = realRow('ses_done_new');
  return {
    ...base, id, title: `T ${id}`, projectID: 'p1', directory: '/repo', state, ownState: state, running: state === 'working',
    idle: state === 'working' || state === 'blocked' ? undefined : NOW - minute, outcome: state === 'finished' ? 'succeeded' : undefined,
    activeAt: NOW - minute, created: NOW - 60 * minute, children: [], pending: { permissions: 0, forms: 0 }, permissions: [], forms: [],
    ...extra,
  };
}

export function wireSnapshot(rows, connection = 'connected', launches = []) {
  return {
    generatedAt: NOW, counts: payloads.snapshot.counts, connection: { status: connection, since: NOW, failures: 0 },
    projects: [
      { id: 'p1', name: 'box', directory: '/repo', worktrees: [
        { directory: '/repo', kind: 'root', rows: rows.filter((r) => r.directory === '/repo') },
        { directory: '/wt/feat-x', kind: 'worktree', rows: rows.filter((r) => r.directory === '/wt/feat-x') },
      ] },
      { id: 'global', name: 'global', directory: '/', worktrees: [
        { directory: '/tmp/scratch', kind: 'directory', rows: rows.filter((r) => r.directory === '/tmp/scratch') },
      ] },
    ],
    launches,
  };
}

/** A launch shaped like Fleet's `Launch`. */
export const wireLaunch = (extra = {}) => ({ ...structuredClone(payloads.snapshot.launches[0]), ...extra });

const tick = () => new Promise((resolve) => setImmediate(resolve));
export const flush = async (n = 10) => { for (let i = 0; i < n; i++) await tick(); };

/** Manual timers: `run(ms)` fires due callbacks in order. */
export function fakeTimers() {
  let now = 0, id = 0;
  const pending = new Map(), intervals = new Set();
  return {
    setTimeout: (fn, ms) => { pending.set(++id, { fn, at: now + ms }); return id; },
    clearTimeout: (handle) => { pending.delete(handle); },
    setInterval: () => { intervals.add(++id); return id; }, clearInterval: (handle) => { intervals.delete(handle); },
    intervals: () => intervals.size,
    delays: () => [...pending.values()].map((t) => t.at - now).sort((a, b) => a - b),
    async run(ms) {
      now += ms;
      for (const [key, t] of [...pending].sort((a, b) => a[1].at - b[1].at)) {
        if (t.at > now) continue;
        pending.delete(key);
        t.fn();
        await flush();
      }
    },
  };
}

/** Streaming SSE body the test pushes into; aborting the request errors the reader. */
function sseStream(signal) {
  let controller;
  const body = new ReadableStream({ start(c) { controller = c; } });
  signal.addEventListener('abort', () => { try { controller.error(new Error('aborted')); } catch { /* closed */ } });
  const encoder = new TextEncoder();
  return {
    response: { ok: true, body },
    send: (text) => controller.enqueue(encoder.encode(text)),
    close: () => controller.close(),
  };
}

const jsonResponse = (status, body) => ({
  ok: status >= 200 && status < 300, status,
  json: async () => { if (body === undefined) throw new SyntaxError('not JSON'); return structuredClone(body); },
});

/**
 * Fake Fleet over `fetch`: the snapshot, the SSE stream, and `respond(method, path, status, body)`
 * answers for every other route (default: Next's HTML 404). `requests()` lists the non-stream
 * calls with their method, path, headers and parsed body.
 */
export function fakeFetch() {
  const calls = [], streams = [], answers = new Map();
  let snapshot = wireSnapshot([wireRow('w', 'working')]);
  let down = false;
  const fetch = async (url, options = {}) => {
    calls.push({ url, options });
    if (down) throw new TypeError('fetch failed');
    const { pathname, search } = new URL(url);
    if (pathname === '/api/fleet') return { ok: true, status: 200, json: async () => structuredClone(snapshot) };
    if (pathname === '/api/fleet/events') {
      const stream = sseStream(options.signal);
      streams.push(stream);
      return stream.response;
    }
    const answer = answers.get(`${options.method ?? 'GET'} ${pathname}${search}`) ?? answers.get(`${options.method ?? 'GET'} ${pathname}`);
    if (typeof answer === 'function') return answer(options);
    return answer ? jsonResponse(answer.status, answer.body) : jsonResponse(404, undefined);
  };
  const requests = () => calls
    .map(({ url, options }) => ({ url, path: new URL(url).pathname + new URL(url).search, method: options.method ?? 'GET', headers: options.headers ?? {}, body: options.body === undefined ? undefined : JSON.parse(options.body), options }))
    .filter((c) => !['/api/fleet', '/api/fleet/events'].includes(new URL(c.url).pathname));
  return {
    fetch, calls, streams, requests,
    setSnapshot: (s) => { snapshot = s; }, setDown: (v) => { down = v; },
    respond: (method, path, status, body) => { answers.set(`${method} ${path}`, typeof status === 'function' ? status : { status, body }); },
  };
}

export const change = (payload) => `event: fleet.changed\ndata: ${JSON.stringify({ connection: { status: 'connected' }, counts: payloads.snapshot.counts, rows: [], removed: [], ...payload })}\n\n`;
