#!/bin/bash

# .env
if [ -f "$HOME/.env" ]; then
    source "$HOME/.env"
else
    echo "Warning: $HOME/.env file not found"
fi

# pnpm
export PNPM_HOME="/Users/magoz/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# Brew
eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="/opt/homebrew/bin:$PATH"

# User shell colors
export CLICOLOR=1

# Environment variables set everywhere
export EDITOR="nvim"
export TERMINAL="iterm2"
export BROWSER="chrome"

# nnn
export NNN_PLUG='v:imgview'

# -------------------------------
#         ANDROID STUDIO
# -------------------------------
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# ---------------------------------------------
#               ORIGINAL CONFIG
# https://github.com/Mach-OS/Machfiles/blob/6373a1fd1e42ca2fd8babd95ef4acce9164c86c3/zsh/.config/zsh/zsh-exports
#
# ---------------------------------------------

export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH="$HOME/.rustup/toolchains/nightly-aarch64-apple-darwin/bin:$PATH"
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH="$PATH:./node_modules/.bin"
# export PATH="/usr/local/opt/postgresql@16/bin:$PATH" // intel mac
export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"
