#!/bin/bash

# VIM
alias v='nvim'
alias vi='nvim'
alias vim='nvim'

# PNPM
alias p=pnpm

# Common directories 
alias dot='cd ~/.dotfiles'

# Quicklook
ql() {
  qlmanage -p "$@" >&/dev/null
}

# MARKDOWN
# Markdown to Clipboard as rich text
md() {
  cat $1 | \
  pandoc --from markdown --to html --ascii | \
  textutil -convert rtf -stdin -stdout -format html | \
  pbcopy -Prefer rtf
}

# Markdown to Clipboard as plain text
md-plain() {
  pandoc -f markdown -t plain $1 --wrap=preserve | pbcopy
}

# ---------------------------------------------
#               ORIGINAL CONFIG
# https://github.com/Mach-OS/Machfiles/blob/6373a1fd1e42ca2fd8babd95ef4acce9164c86c3/zsh/.config/zsh/zsh-aliases
#
# ---------------------------------------------

alias j='z'
alias f='zi'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'
