# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 20
inner.vertical =   20
outer.left =       20
outer.bottom =     20
outer.top =        20
outer.right =      20

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'


############################################################
# FOCUS & REARRANGE WINDOWS
############################################################

# Alt is for managing window focus.
# Ctrl is for everything else.
# This is because alt+numbers is used to output characters like €, £, etc.

###############
# Focus
###############

# See: https://nikitabobko.github.io/AeroSpace/commands#focus-back-and-forth
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-enter = 'focus-back-and-forth'

###############
# Move
###############

# See: https://nikitabobko.github.io/AeroSpace/commands#move
ctrl-alt-h = 'move left'
ctrl-alt-j = 'move down'
ctrl-alt-k = 'move up'
ctrl-alt-l = 'move right'

# Merge current window with the window in the specified direction
ctrl-alt-cmd-h = ['join-with left', 'mode main']
ctrl-alt-cmd-j = ['join-with down', 'mode main']
ctrl-alt-cmd-k = ['join-with up', 'mode main']
ctrl-alt-cmd-l = ['join-with right', 'mode main']


###############
# Rearrange
###############

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
ctrl-minus = 'resize smart -50'
ctrl-equal = 'resize smart +50'

###############
# Layouts
# See: https://nikitabobko.github.io/AeroSpace/commands#layout
###############

# Toggle between Fullscreen an tilling layout
ctrl-alt-f = 'fullscreen'

# Toggle between Floating and tiling layout
ctrl-alt-t = 'layout floating tiling'

# Toggle between Horizontal and Vertical layout
ctrl-alt-slash = 'layout tiles horizontal vertical'


############################################################
# WORKSPACES
############################################################

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
ctrl-1  = 'workspace 1'
ctrl-2  = 'workspace 2'
ctrl-3  = 'workspace 3'
ctrl-4  = 'workspace 4'
ctrl-5  = 'workspace 5'
ctrl-6  = 'workspace 6'
ctrl-7  = 'workspace 7'
ctrl-8  = 'workspace 8'
ctrl-9  = 'workspace 9'
ctrl-0  = 'workspace 10'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
ctrl-alt-1 = ['move-node-to-workspace 1', 'workspace 1']
ctrl-alt-2 = ['move-node-to-workspace 2', 'workspace 2']
ctrl-alt-3 = ['move-node-to-workspace 3', 'workspace 3']
ctrl-alt-4 = ['move-node-to-workspace 4', 'workspace 4']
ctrl-alt-5 = ['move-node-to-workspace 5', 'workspace 5']
ctrl-alt-6 = ['move-node-to-workspace 6', 'workspace 6']
ctrl-alt-7 = ['move-node-to-workspace 7', 'workspace 7']
ctrl-alt-8 = ['move-node-to-workspace 8', 'workspace 8']
ctrl-alt-9 = ['move-node-to-workspace 9', 'workspace 9']
ctrl-alt-0 = ['move-node-to-workspace 10', 'workspace 10']

# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
ctrl-alt-m = 'move-workspace-to-monitor --wrap-around next'


############################################################
# BINDING MODES
############################################################

# # See: https://nikitabobko.github.io/AeroSpace/commands#mode
# ctrl-comma = 'mode service'
#
# # 'service' binding mode declaration.
# # See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# [mode.service.binding]
# esc = ['reload-config', 'mode main']
# r = ['flatten-workspace-tree', 'mode main'] # reset layout
# f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
# backspace = ['close-all-windows-but-current', 'mode main']


############################################################
# AUTOMATION
############################################################

###############
# Monitors
###############

# Assign workspaces to monitors
# See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
# [workspace-to-monitor-force-assignment]
# 1 = 1                            # Monitor sequence number from left to right. 1-based indexing
# 2 = 'main'                       # Main monitor
# 3 = 'secondary'                  # Non-main monitor in case when there are only two monitors
# 4 = 'built-in'                   # Case insensitive regex substring
# 5 = '^built-in retina display$'  # Case insensitive regex match
# 6 = ['secondary', 'dell']        # You can specify multiple patterns. The first matching pattern will be used

[workspace-to-monitor-force-assignment]
10 = '^built-in retina display$' # Assign workspace 10 to the buit-in retina display

###############
# Default Application Workspace
###############

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.googlecode.iterm2'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'ru.keepcoder.Telegram'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 9'

###############
# App patches
###############

[[on-window-detected]]
if.window-title-regex-substring = '^(Picture in Picture|Picture-in-Picture)$'
run = 'layout floating'
check-further-callbacks = true

# [[on-window-detected]]
# if.app-id="com.mitchellh.ghostty"
# run= [
#   "layout tiling",
# ]

###############
# Experimental
###############

# Automerge new windows to the most right one
# TODO: Implement when it works:
# https://github.com/nikitabobko/AeroSpace/issues/20#issuecomment-2293140662
# [[on-window-detected]]
# run = ['join-with right', 'mode main']
