#!/usr/bin/env node
// Generates OpenCode agents (agents/*.md) from the shared agent definitions in
// ~/.agents/agents/*.md, which Pi reads natively. The shared file owns name,
// description, model, thinking, tools and the prompt body; this script only
// translates Pi frontmatter to OpenCode's model#variant and permission rules.
//   node scripts/sync-agents.mjs          write agents/*.md
//   node scripts/sync-agents.mjs --check  exit 1 when agents/*.md are stale
import { realpathSync } from 'node:fs';
import { readdir, readFile, writeFile, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

export const SOURCE = fileURLToPath(new URL('../../../../agents/.agents/agents/', import.meta.url));
export const TARGET = fileURLToPath(new URL('../agents/', import.meta.url));
const MARKER = '# Generated by scripts/sync-agents.mjs';

const VARIANTS = new Set(['low', 'medium', 'high', 'xhigh', 'max']);
const allow = (action, resource = '*') => ({ action, resource, effect: 'allow' });
const deny = (action, resource = '*') => ({ action, resource, effect: 'deny' });
// Child rules replace the global allow-all, so repeat the global secret-read denies.
const SECRET_READS = [deny('read', '*.env'), deny('read', '*.env.*'), allow('read', '.env.example'),
  deny('read', '*.envrc'), deny('read', 'secrets/*')];
// Pi tool name -> OpenCode permission rules. Unknown tools fail loudly.
const TOOLS = {
  read: [allow('read'), ...SECRET_READS],
  grep: [allow('grep')],
  find: [allow('glob')],
  ls: [allow('glob')],
  bash: [allow('shell')],
  edit: [allow('edit')],
  write: [allow('edit')],
  websearch: [allow('websearch')],
  webfetch: [allow('webfetch')],
  contact_supervisor: [], // Pi-only; agent prompts fall back to returning the question.
};
// Read-only children may read local repos and OpenCode-managed references (project
// `references`, e.g. ../yolk-sdk). Writers stay confined: external_directory gates edit too.
const REFERENCE_DIRS = ['~/dev/repos/**', '~/.local/share/opencode/repos/**'];
const isReadOnly = (tools) => tools.includes('read') && !tools.some((tool) => ['edit', 'write', 'bash'].includes(tool));
// OpenCode-only differences that Pi frontmatter cannot express.
const OVERRIDES = {
  // opencode-go DeepSeek Flash has no `medium` variant; use the model default.
  'web-researcher': { variant: null },
  // Reads ~/aha/SKILL.md and writes its page under /tmp/aha-<slug>/.
  aha: { permissions: [allow('external_directory', '~/aha/**'), allow('external_directory', '/tmp/aha-*')] },
};

export function parse(text, file) {
  const match = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(text);
  if (!match) throw new Error(`${file}: missing frontmatter`);
  const fields = {};
  for (const line of match[1].split('\n')) {
    const field = /^([A-Za-z][\w-]*):\s*(.*)$/.exec(line);
    if (field) fields[field[1]] = field[2].trim();
  }
  for (const key of ['name', 'description', 'model']) {
    if (!fields[key]) throw new Error(`${file}: missing ${key}`);
  }
  return { fields, body: match[2].trim() };
}

export function permissions(name, tools) {
  const rules = [deny('*')];
  const seen = new Set();
  for (const tool of tools) {
    const mapped = TOOLS[tool];
    if (!mapped) throw new Error(`${name}: no OpenCode mapping for Pi tool "${tool}"`);
    for (const rule of mapped) {
      const key = JSON.stringify(rule);
      if (!seen.has(key)) rules.push(rule), seen.add(key);
    }
  }
  const references = isReadOnly(tools) ? REFERENCE_DIRS.map((dir) => allow('external_directory', dir)) : [];
  return [...rules, ...references, ...(OVERRIDES[name]?.permissions ?? [])];
}

export function render(file, text) {
  const { fields, body } = parse(text, file);
  const name = fields.name;
  if (`${name}.md` !== path.basename(file)) throw new Error(`${file}: name "${name}" must match file name`);
  const override = OVERRIDES[name] ?? {};
  const variant = override.variant === undefined ? fields.thinking : override.variant;
  if (variant && !VARIANTS.has(variant)) throw new Error(`${name}: unknown thinking level "${variant}"`);
  const tools = (fields.tools ?? '').split(',').map((tool) => tool.trim()).filter(Boolean);
  const model = variant ? `${fields.model}#${variant}` : fields.model;
  return [
    '---',
    `${MARKER} from ~/.agents/agents/${name}.md; edit the source, then run \`npm run sync:agents\`.`,
    `description: ${JSON.stringify(fields.description)}`,
    'mode: "subagent"',
    `model: ${JSON.stringify(model)}`,
    `permissions: ${JSON.stringify(permissions(name, tools))}`,
    '---',
    '',
    body,
    '',
  ].join('\n');
}

export async function plan() {
  const sources = (await readdir(SOURCE)).filter((entry) => entry.endsWith('.md')).sort();
  const want = new Map();
  for (const entry of sources) want.set(entry, render(entry, await readFile(path.join(SOURCE, entry), 'utf8')));
  const writes = [];
  for (const [entry, text] of want) {
    const current = await readFile(path.join(TARGET, entry), 'utf8').catch(() => undefined);
    if (current !== text) writes.push({ entry, text });
  }
  // Only remove files this script generated; hand-written agents stay.
  const removals = [];
  for (const entry of await readdir(TARGET)) {
    if (!entry.endsWith('.md') || want.has(entry)) continue;
    if ((await readFile(path.join(TARGET, entry), 'utf8')).includes(MARKER)) removals.push(entry);
  }
  return { writes, removals };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === realpathSync(process.argv[1])) {
  const { writes, removals } = await plan();
  if (process.argv.includes('--check')) {
    for (const { entry } of writes) console.error(`stale: agents/${entry}`);
    for (const entry of removals) console.error(`orphaned: agents/${entry}`);
    process.exit(writes.length || removals.length ? 1 : 0);
  }
  for (const { entry, text } of writes) await writeFile(path.join(TARGET, entry), text), console.log(`wrote agents/${entry}`);
  for (const entry of removals) await rm(path.join(TARGET, entry)), console.log(`removed agents/${entry}`);
}
