#!/bin/bash

fpath+="$ZDOTDIR/plugins/pure"

autoload -U promptinit; promptinit

# change the dit color indicator
zstyle :prompt:pure:git:dirty color yellow

# turn on git stash status
zstyle :prompt:pure:git:stash show yes

prompt pure

